// Generated by CoffeeScript 1.9.0
(function() {
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.initialize = function() {
      this.newGameSetup();
      this.set('bank', new Bank({
        balance: 1000,
        betAmount: 100
      }));
      return this.set('bankView', new BankView({
        model: this.get('bank')
      }));
    };

    App.prototype.newGame = function() {
      this.newGameSetup();
      return this.trigger('newGame');
    };

    App.prototype.newGameSetup = function() {
      var deck;
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      this.set('dealerHand', deck.dealDealer());
      this.get('playerHand').on('bust', (function(_this) {
        return function() {
          _this.trigger('playerLoses');
          return _this.get('bank').trigger('loseBet');
        };
      })(this));
      this.get('dealerHand').on('bust', (function(_this) {
        return function() {
          _this.trigger('playerWins');
          return _this.get('bank').trigger('winBet');
        };
      })(this));
      return this.get('playerHand').on('stand', (function(_this) {
        return function() {
          var dealerScore, playerScore;
          _this.get('dealerHand').dealerDraw();
          playerScore = _this.get('playerHand').maxScore();
          dealerScore = _this.get('dealerHand').maxScore();
          if (dealerScore < playerScore && dealerScore <= 21) {
            _this.trigger('playerWins');
            _this.get('bank').trigger('winBet');
          }
          if (dealerScore > playerScore && dealerScore <= 21) {
            _this.trigger('playerLoses');
            _this.get('bank').trigger('loseBet');
          }
          if (dealerScore === playerScore) {
            return _this.trigger('tieGame');
          }
        };
      })(this));
    };

    return App;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=App.js.map
