// Generated by CoffeeScript 1.9.0
(function() {
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  window.Bank = (function(_super) {
    __extends(Bank, _super);

    function Bank() {
      return Bank.__super__.constructor.apply(this, arguments);
    }

    return Bank;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=Bank.js.map

