// Generated by CoffeeScript 1.9.0
(function() {
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  window.AppView = (function(_super) {
    __extends(AppView, _super);

    function AppView() {
      return AppView.__super__.constructor.apply(this, arguments);
    }

    AppView.prototype.template = _.template("<h1>Black Jack</h1> <center> <div class='buttons'> <button class='hit-button btn btn-primary'>Hit</button> <button class='stand-button btn btn-warning'>Stand</button> <button class='new-game-button btn btn-info'>New Game</button> </div> </center> <hr> <div class='player-hand-container'></div> <div class='dealer-hand-container'></div>");

    AppView.prototype.events = {
      'click .hit-button': function() {
        return this.model.get('playerHand').hit();
      },
      'click .stand-button': function() {
        return this.model.get('playerHand').stand();
      },
      'click .new-game-button': function() {
        return this.model.newGame();
      }
    };

    AppView.prototype.initialize = function() {
      this.render();
      this.model.on('playerLoses', (function(_this) {
        return function() {
          _this.$el.prepend('<center><div class="game-result-lose alert alert-danger">You lost.</div></center>');
          $('.game-result-lose').hide().fadeIn().delay(1000).fadeOut();
          return setTimeout(_this.model.newGame.bind(_this.model), 1800);
        };
      })(this));
      this.model.on('playerWins', (function(_this) {
        return function() {
          _this.$el.prepend('<center><div class="game-result-win alert alert-success">You win!</div></center>');
          $('.game-result-win').hide().fadeIn().delay(1000).fadeOut();
          return setTimeout(_this.model.newGame.bind(_this.model), 1800);
        };
      })(this));
      this.model.on('tieGame', (function(_this) {
        return function() {
          _this.$el.prepend('<center><div class="game-result-tie alert alert-warning">You tied!</div></center>');
          $('.game-result-tie').hide().fadeIn().delay(1000).fadeOut();
          return setTimeout(_this.model.newGame.bind(_this.model), 1800);
        };
      })(this));
      this.model.on('newGame', (function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
      if (this.model.get('playerHand').maxScore() === 21) {
        return this.model.get('playerHand').stand();
      }
    };

    AppView.prototype.render = function() {
      this.$el.children().detach();
      this.$el.html(this.template());
      this.$('.player-hand-container').html(new HandView({
        collection: this.model.get('playerHand')
      }).el);
      return this.$('.dealer-hand-container').html(new HandView({
        collection: this.model.get('dealerHand')
      }).el);
    };

    return AppView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=AppView.js.map
