// Generated by CoffeeScript 1.9.0
(function() {
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  window.BankView = (function(_super) {
    __extends(BankView, _super);

    function BankView() {
      return BankView.__super__.constructor.apply(this, arguments);
    }

    BankView.prototype.el = $('.bank-container');

    BankView.prototype.className = 'bank';

    BankView.prototype.template = _.template('<div>Balance: <%= balance %></div><div>Bet: <%= betAmount %></div><button class="increase-bet btn btn-success">+10</button> <button class="decrease-bet btn btn-danger">-10</button>');

    BankView.prototype.initialize = function() {
      this.render();
      this.model.on('change', (function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
      this.model.on('loseBet', (function(_this) {
        return function() {
          return _this.model.set('balance', _this.model.get('balance') - _this.model.get('betAmount'));
        };
      })(this));
      return this.model.on('winBet', (function(_this) {
        return function() {
          return _this.model.set('balance', _this.model.get('balance') + _this.model.get('betAmount'));
        };
      })(this));
    };

    BankView.prototype.render = function() {
      this.$el.children().detach();
      return this.$el.html(this.template(this.model.attributes));
    };

    BankView.prototype.events = {
      'click .increase-bet': function() {
        return this.model.set('betAmount', this.model.get('betAmount') + 10);
      },
      'click .decrease-bet': function() {
        return this.model.set('betAmount', this.model.get('betAmount') - 10);
      }
    };

    return BankView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=BankView.js.map
