// Generated by CoffeeScript 1.9.0
(function() {
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  window.CardView = (function(_super) {
    __extends(CardView, _super);

    function CardView() {
      return CardView.__super__.constructor.apply(this, arguments);
    }

    CardView.prototype.className = 'card';

    CardView.prototype.template = _.template('');

    CardView.prototype.initialize = function() {
      return this.render();
    };

    CardView.prototype.render = function() {
      var bgUrl;
      this.$el.children().detach();
      this.$el.html(this.template(this.model.attributes));
      if (!this.model.get('revealed')) {
        this.$el.addClass('covered');
      }
      bgUrl = "url('img/cards/" + (this.model.get('rankName')) + "-" + (this.model.get('suitName')) + ".png')";
      this.$el.css({
        'background': bgUrl,
        'background-size': '100px, 140px'
      });
      if (!this.model.get('revealed')) {
        return this.$el.css({
          'background': "url('img/card-back.png')",
          'background-size': '100px, 140px'
        });
      }
    };

    return CardView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=CardView.js.map
