// Generated by CoffeeScript 1.9.0
(function() {
  var assert, expect;

  assert = chai.assert;

  expect = chai.expect;

  describe("app constructor", function() {
    return describe("newGame", function() {
      it("should start a new game upon initialization", function() {
        var app;
        app = new App();
        return expect(app.newGameSetup).to.be.called;
      });
      return it("should ", function() {
        var app;
        app = new App();
        app.get('playerHand').bust();
        return expect(app.trigger).to.be.called;
      });
    });
  });

}).call(this);

//# sourceMappingURL=AppSpec.js.map
