// Generated by CoffeeScript 1.9.0
(function() {
  var assert, expect;

  assert = chai.assert;

  expect = chai.expect;

  describe("hand constructor", function() {
    describe("hit method", function() {
      it("should have a hit method", function() {
        var hand;
        hand = new Hand();
        return expect(hand.hit).to.be.ok;
      });
      return it("should have a length of 4 after hit is called twice", function() {
        var deck, hand;
        deck = new Deck();
        hand = deck.dealPlayer();
        hand.hit();
        hand.hit();
        return expect(hand.length).to.equal(4);
      });
    });
    describe("bust method", function() {
      it("should have a bust method", function() {
        var hand;
        hand = new Hand();
        return expect(hand.bust).to.be.ok;
      });
      return it("should call bust when maxScore is over 21", function() {
        var deck, hand;
        deck = new Deck();
        hand = new Hand([11, 10], deck);
        hand.hit();
        return expect(hand.bust).to.be.called;
      });
    });
    it("should have a stand method", function() {
      var hand;
      hand = new Hand();
      return expect(hand.stand).to.be.ok;
    });
    describe("dealerDraw method", function() {
      it("should have a dealerDraw method", function() {
        var deck, hand;
        deck = new Deck();
        return hand = deck.dealPlayer();
      });
      it("should flip card when dealerDraw is invoked", function() {
        var deck, hand;
        deck = new Deck();
        hand = deck.dealPlayer();
        hand.dealerDraw();
        return expect(deck.first().flip).to.be.called;
      });
      return it("should hit if dealerScore is less than 17", function() {
        var deck, hand;
        deck = new Deck();
        hand = new Hand([1, 2], deck);
        hand.dealerDraw();
        return expect(hand.hit).to.be.called;
      });
    });
    describe("hasAce method", function() {
      it("should have a hasAce method", function() {
        var hand;
        hand = new Hand();
        return expect(hand.hasAce).to.be.ok;
      });
      it("should equal false when no ace is present", function() {
        var card1, deck, hand;
        deck = new Deck();
        card1 = new Card({
          rank: 0
        });
        hand = new Hand([card1, 2], deck);
        return expect(hand.hasAce()).to.equal(false);
      });
      return it("should equal true when ace is present", function() {
        var card1, deck, hand;
        deck = new Deck();
        card1 = new Card({
          rank: 1
        });
        hand = new Hand([card1, 2], deck);
        return expect(hand.hasAce()).to.equal(true);
      });
    });
    describe("minScore method", function() {
      it("should have a minScore method", function() {
        var hand;
        hand = new Hand();
        return expect(hand.minScore).to.be.ok;
      });
      it("should calculate the minScore of two Cards", function() {
        var card1, card2, deck, hand;
        deck = new Deck();
        card1 = new Card({
          rank: 10
        });
        card2 = new Card({
          rank: 0
        });
        hand = new Hand([card1, card2], deck);
        return expect(hand.minScore()).to.equal(20);
      });
      return it("should ignore flipped cards", function() {
        var card1, card2, deck, hand;
        deck = new Deck();
        card1 = new Card({
          rank: 10
        });
        card2 = new Card({
          rank: 0
        });
        card2.flip();
        hand = new Hand([card1, card2], deck);
        return expect(hand.minScore()).to.equal(10);
      });
    });
    describe("maxScore method", function() {
      it("should have a maxScore method", function() {
        var hand;
        hand = new Hand();
        return expect(hand.maxScore).to.be.ok;
      });
      return it("should calculate the maxScore of two Cards when an ace is present", function() {
        var card1, card2, deck, hand;
        deck = new Deck();
        card1 = new Card({
          rank: 1
        });
        card2 = new Card({
          rank: 0
        });
        hand = new Hand([card1, card2], deck);
        return expect(hand.maxScore()).to.equal(21);
      });
    });
    return describe("score method", function() {
      it("should have a scores method", function() {
        var hand;
        hand = new Hand();
        return expect(hand.scores).to.be.ok;
      });
      return it("should be an array with two values", function() {
        var card1, card2, deck, hand;
        deck = new Deck();
        card1 = new Card({
          rank: 5
        });
        card2 = new Card({
          rank: 1
        });
        hand = new Hand([card1, card2], deck);
        expect(hand.scores()[0]).to.equal(6);
        return expect(hand.scores()[1]).to.equal(16);
      });
    });
  });

}).call(this);

//# sourceMappingURL=HandSpec.js.map
